### ISSUE TITLE
Choisir une convention pour la version stable

### ISSUE THREAD

**Issue by ksamuel** [PnX-SI/UsersHub-authentification-module#10]
Le projet de gestion d'autorisations du parc du mercantour va bientôt être mis en production. Il contient une dépendance directe vers UsersHub-authentification-module.

Comme UsersHub-authentification-module n'est pas en ligne sur Pypi, on ne peut pas limiter l'installation à une version en particulier pour le moment. Si UsersHub-authentification-module
 évolue, il pourrait casser la compatibilité et donc les futures installations de l'outil du mercantour, ou d'autres futures dépendances.

Afin d'éviter cela, 2 possibilités:

- publier UsersHub-authentification-module. C'est probablement la solution la plus propre, mais aussi la plus longue.
- déclarer la branche master comme une branche perpétuellement stable, et ne pusher que sur une branche de dev. La branche master ne merge que sur des tags de release, que l'on référence alors dans requirements.txt.

Je peux prendre du temps pour aider à la mise en place d'une solution ou l'autre, néanmoins n'ayant pas les droits d'accès, je ne peux le faire moi-même.

**Comment by amandine-sahl** [comment]
Il faudrait effectivement publier le module ce serait plus propre. 

Sinon pour ce qui est des numéros de version il est possible d'indiquer le numéro d'une release dans requirements.txt
Exemple : git+https://github.com/PnX-SI/UsersHub-authentification-module@1.0.1

**Comment by camillemonchicourt** [comment]
- Faire une release avec les commits présents dans la Master (améliorations de @ksamuel)
- Tester puis faire une autre release avec les commits présents dans la branche Develop (pour gérer les besoins du CRUVED utilisés dans GeoNature V2)
- Faire les évolutions pour pouvoir utiliser le nouveau champs `pass_plus` de UsersHub (https://github.com/PnX-SI/UsersHub-authentification-module/issues/11) et faire une release.

**Comment by camillemonchicourt** [comment]
Sur les releases : 

- Pas de ``v`` dans les tags de versions, sinon ça pose des soucis quand dans un ``settings.ini`` on veut parfois faire appel à une branche, parfois à une release.
- On incrémente le 3° chiffre quand il y a uniquement des corrections
- On incrémente le 2° chiffre quand il y a des nouveautés
- On incrémente le fichier VERSION avant une Release et juste après (x.y.z.dev0)

Pour faire les CHANGELOG, utiliser le comparateur de branches.

- Pour la future 1.1.0 (si on en fait une intégrant uniquement le CRUVED) : https://github.com/PnX-SI/UsersHub-authentification-module/compare/1.0.2...develop
- Pour la future 1.2.0 (intégrant le pass_plus) : https://github.com/PnX-SI/UsersHub-authentification-module/compare/1.0.2...pass_plus

**Comment by camillemonchicourt** [comment]
Sortie de la 1.1.0 intégrant toutes les évolutions.
