### ISSUE TITLE
Pouvoir utiliser le champs PASS_PLUS

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/UsersHub-authentification-module#11]
La version 1.3.0 de UsersHub intègre un champs mot de passe `pass_plus` plus robuste que le champs initial `pass` encodé en md5 : https://github.com/PnEcrins/UsersHub/releases/tag/1.3.0

En effet ce nouveau champs utilise un système de hashage. 

Une évolution doit être fait dans le module d'authentification pour pouvoir choisir le mode d'encodage utilisé et donc le champs à utiliser.

**Comment by amandine-sahl** [comment]
C'est possible grace à bcrypt même si ça reste à faire

```
import bcrypt
import psycopg2

conn_string = "host='localhost' dbname='mabase' user='monuser' password='monpass'"
conn = psycopg2.connect(conn_string)
cursor = conn.cursor()
print "Connected!\n"

cursor.execute("SELECT pass_plus FROM utilisateurs.t_roles WHERE id_role = 196")
records = cursor.fetchall()
pass_plus = records[0][0]

password = "super password"

if bcrypt.checkpw(password, pass_plus):
    print "It matches"
else:
    print "It does not match"

```

**Comment by camillemonchicourt** [comment]
Fait dans la branche ``pass_plus``. 
A merger dans ``develop`` quand c'est stabilisé puis faire une release.

**Comment by camillemonchicourt** [comment]
Fait dans la version 1.1.0.
