### ISSUE TITLE
Doublons et champs dans t_role

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/UsersHub-authentification-module#17]
Dans t_roles, les roles sont associés à la fois à un id_organisme, et à un organisme. 

Il y a une contrainte là dessus? Pourquoi avoir cette info en double, avec un risque d'erreur? 

Autre question : le champ "pn" a-t-il une utilité? A-t-il vocation à être conservé ?

**Comment by camillemonchicourt** [comment]
Tu es pas sur le bon dépôt. 
C'est identifié et supprimé dans la V2 https://github.com/PnEcrins/UsersHub/issues/38

Idem pour le champ pn

**Comment by DonovanMaillard** [comment]
merci.... je retourne voir sur l'autre dépot :D
