### ISSUE TITLE
Le schéma ne correspond pas aux modèles de la base de données 

### ISSUE THREAD

**Issue by HamoudaAmine** [PnX-SI/UsersHub-authentification-module#18]
Dans db le schema.sql ne correspond pas au models.py

j'ai eu les erreurs suivante  lorsque j'utilise la route login : 

- "POST /api/auth/login HTTP/1.1" 500 -
(psycopg2.ProgrammingError) ERREUR: la colonne v_userslist_forall_applications.pass_plus n'existe pas
LINE 1: ...tilisateurs_v_userslist_forall_applications_pass, utilisateu…

- ERREUR: la colonne t_applications.id_parent n'existe pas
LINE 3: WHERE utilisateurs.t_applications.id_parent = '10' AND utili…

**Comment by camillemonchicourt** [comment]
Oui, voir https://github.com/PnX-SI/UsersHub-authentification-module/issues/2#issuecomment-436993110

Et la doc d'utilisation/installation complétée cette semaine dans la branche ``develop`` : https://github.com/PnX-SI/UsersHub-authentification-module/blob/develop/README.md

**Comment by camillemonchicourt** [comment]
SQL du schéma retiré du sous-module : https://github.com/PnX-SI/UsersHub-authentification-module/commit/66bb152f1e5930dfac15d7764de7644ab834a342
Et doc complétée.
