### ISSUE TITLE
Utilisation de l'api de usershub

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/UsersHub-authentification-module#23]
La pull request #22  intègre le travail réalisé par @joelclems

Rajout des fonctionnalités suivantes: 
* Réaliser des actions après avoir fait un appel à l'API de usershub
* Connexion automatique d'un utilisateur administrateur de l'application

Une application exemple d'utilisation des fonctionnalités est disponible : https://github.com/PnX-SI/test_client_usershub_api

![userhub_api](https://user-images.githubusercontent.com/3088650/54835016-985ad700-4cc1-11e9-915b-3d71c1b36754.jpg)

**Comment by camillemonchicourt** [comment]
Fait dans la 1.4.0
