### ISSUE TITLE
Cookie : paramètre Path toujours égal à "/"

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/UsersHub-authentification-module#69]
Dans le cadre d'une prestation pour l'Agence Régionale de la Biodiversité en île de France, je me suis aperçu que le cookie avait comme `Path` la valeur `/`. 
GeoNature étant sur l'url `/geonature`, il faut que le cookie ait un `Path` de valeur `/geonature` car pourrait interférer avec les cookies du site hébergé sur `/`

Dans UsersHub-authentification-module, ce dernier ne semble pas paramétrable : https://github.com/PnX-SI/UsersHub-authentification-module/blob/049c25c984e758272226e3ebefe151194f277f99/src/pypnusershub/routes.py#L246

Alors qu'il est possible de le faire. Cf doc : https://flask.palletsprojects.com/en/2.2.x/api/#flask.Response.set_cookie

Pour le rendre paramétrable, je me pose donc la question suivante : sachant que la variable `APPLICATION_ROOT` est à `/` par défaut, serait-il possible de s'en servir pour configurer le `Path` du cookie ? 

Merci d'avance pour vos retours !

**Comment by TheoLechemia** [comment]
Salut Maxime,
Dans cette PR, j'ai commencé à solutionné ce problème : https://github.com/PnX-SI/UsersHub-authentification-module/pull/68
On arrêterait d'utiliser les cookie pour GN, TaxHub (mais conservé pour UsersHub avec le mécanisme integré à Flask-Login), au profit d'un Header Authorization. Donc plus de conflit possible de cookie entre les apps.
Par contre c'est pas au programme de la 2.13. Il y a encore un peu de boulot sur cette PR, mais l'idée est de la mergé une fois la 2.13 sortie.

**Comment by mvergez** [comment]
Salut Théo !

Merci pour ton retour rapide !
Effectivement j'avais vu passer cette PR, super initiative en tout cas !

Oui ça solutionnerait le problème. Je me disais effectivement qu'on pourrait mitiger le soucis du cookie en attendant la prochaine version. 
A tester mais rajouter un app_config["APPLICATION_ROOT"] ne devrait pas trop poser de souci, mais je sais pas s'il est utilisé ailleurs comme c'est un paramètre qu'on a plus l'habitude de mettre dans GeoNature... Qu'en penses-tu ?

**Comment by camillemonchicourt** [comment]
Fait dans la 1.6.8.
