### ISSUE TITLE
Bug lors de la demande d'inscription 

### ISSUE THREAD

**Issue by ch-cbna** [PnX-SI/UsersHub-authentification-module#91]
**Version**
develop (GN > 2.13.4 & UH > 2.4.0)

**Comment reproduire ?**
Lorsque l'on clique sur le bouton "S'inscrire", une erreur s'affiche (voir l'image ci-dessous).

**Remarques**
Cette erreur est sûrement causée par la montée en version de SQLAlchemy. 

**Solution**
Supprimer [cette ligne](https://github.com/PnX-SI/UsersHub-authentification-module/blob/344bdda4c702e3ce21fd4600735cca6f78acbb70/src/pypnusershub/routes_register.py#L103), la requête  `.first()` ne renvoyant pas une liste, mais bien la valeur "brute" pour `id_app_usershub`.

![image](https://github.com/PnX-SI/UsersHub-authentification-module/assets/102586824/c16c4373-ef68-4468-85db-abe1c7c63e30)

**Comment by camillemonchicourt** [comment]
Quelle version des outils ?

**Comment by jacquesfize** [comment]
Merci pour ton retour ! J'ai intégré le fix sur la PR #92.
