### ISSUE TITLE
Suivi authentification

### ISSUE THREAD

**Issue by lpojgc** [PnX-SI/UsersHub-authentification-module#98]
Bonjour,
Est-ce qu'il a été envisagé de logguer les authentifications (par module) ? Est-ce possible facilement ?
L'intérêt pour nous serait d'identifier :

- les comptes à désactiver (objectif principal),
- les utilisateurs à accompagner car n'utilisant pas les outils sans faire de retour (objectif secondaire).

Merci

**Comment by camillemonchicourt** [comment]
Ce n'est pas prévu et je ne suis pas certain que cela soit une pratique souhaitable au regard de la protection des données personnelles.
